### ISSUE TITLE
Items to do for launch

### ISSUE THREAD

**Issue by ejsandoval** [processing/processing-website#92]
This is a super issue for tracking all the work that needs to be done before we launch the new processing.org website!

## Completed

- [x] **Books list**. We need to port the content from Books. Follow the guide [here](https://github.com/processing/processing-website/blob/master/docs/books.md)
- [x] **`sound` and `video` references (Processing)**. We will need to move the references for these libraries into a JavaDoc format that lives within the source code of each of these libraries. You can follow [this guide](https://github.com/processing/processing-website/blob/master/docs/reference.md) to figure out how to add them to the new website. @Anadroid 
- [x] Footer covers content. Re-visit the way the header, sidebar and footer works.
- [x] New layout for "Participate"
- [x] Highlight current title on table of contents.
- [x] Donate page with DonorBox.
- [x] The search component on the main menu does not work.
- [x] Make front page live sketch accessible with keyboard (change numbers, etc)
- [x] Check examples content on branch `more-content`
- [x] **Missing reference examples images** for: `push()`, `pop()`, `square()`, `endContour()`, `circle()`
- [x] Check that all pages are responsive and look good on tablets and mobile screens. PR #119 
- [x] Reference: Figure out what class methods to show / not show under `sound`, `video`, etc + Add Sound images
- [x] Method pages should have a field with class to whom they belong to 
- [x] Fix mobile menu PR #114 
- [x] Reference: PGraphics should only have 2 methods PR #117 
- [x] **In use (Processing)**. We need to go through the references and add links to examples shown under the "In use" section  PR #120 
- [x] The CSS grid system should use `mixin` instead of functions. Make a debug grid component that overlays the grid on the content and check that everything aligns. @bravomartin 
- [x] Add padding top and bottom to `main` or all pages to make the content breathe. @bravomartin 
- [x] Buttons should be square instead of round and with a hover effect that is a simpler version of the code editor button on the front page. @Anadroid  
- [x] Add a `max-width` container that sits on all content except the header, footer, and sidebar. @bravomartin 
- [x] Check `FilterBar` everywhere
- [x] Clean up CSS variables
- [x] Why does `splice()`in reference look bad?
- [x] **P5 code examples**. We need to add P5 code that shows the images/animations on the Example pages.
- [x] Fix `nowrap` parameters length in reference (check `splice()`)
- [x] use `ExampleItem` in related examples @Anadroid 
- [x] Why is RadialGradient and LinearGradient image not loading?
- [x] Look at `button-effect` branch @runemadsen 
- [x] Figure out sidebar / content layout in mobil @bravomartin 
- [x] Responsive design checkup @runemadsen
  - [x] Home
  - [x] Download
  - [x] Reference
  - [x] Reference item
  - [x] Environment
  - [x] Libraries
  - [x] Library item
  - [x] Tools
  - [x] Tutorials
  - [x] Tutorial
  - [x] Examples
  - [x] Example
  - [x] Books
  - [x] About
  - [x] People
  - [x] Donate
- [x] Check vertical spacing classes @runemadsen 
- [x] Donate widget and link to donate page @bravomartin 
- [x] Make room for donate widget on examples pages @runemadsen 
- [x] Update to new logos
- [x] Better mobile top nav @bravomartin 
- [x] Look at two-column image/code layouts for tutorials @Anadroid

**Comment by runemadsen** [comment]
<img width="504" alt="Screen Shot 2021-06-07 at 9 44 28 AM" src="https://user-images.githubusercontent.com/192021/120978624-f6761680-c774-11eb-97bd-bcc6d30afc1c.png">
@bravomartin noticed there's a bit of weirdness in the mobile menu. Not sure if this has been there always.

**Comment by bravomartin** [comment]
🙌
-- 
MB
https://designsystems.international
